<a href="https://colab.research.google.com/github/subhamdasthakur1995/EDA_on-_GLOBAL_TERRORISM/blob/main/EDA_ON_GLOBAL_TERRORISM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Project Name**    -

##### **Project Type**    - EDA
##### **Contribution**    - Team
##### **Team Member 1 -** SUBHAM DAS THAKUR
##### **Team Member 2 -** ARUP MUKHERJEE

 **Project Summary -**

![terror.jpg]()

The Global Terrorist database contains a detailed information about the terrorism, from 1970 to 2017. There are 181691 records and 135 columns including date, country, target details, attack type, and also if there was a motive behind a attack, the outcome of attack, and weapon details. The database is maintained by researchers at the National Consortium for the Study of Terrorism and Responses to Terrorism (START), headquartered at the University of Maryland. For Hackathon we have dropped columns having more than 50% NULL data and would be using the remainder of 60 attributes to present our analysis. we here by state that we have used this data materials solely for non-commercial analysis and Visualization purpose.

# **GitHub Link -**

Provide your GitHub Link here.

# **Problem Statement**

The problem in global terrorism is the persistent threat posed by acts of terrorism across different regions of the world. Terrorism is characterized by the intentional use of violence, intimidation, and fear to achieve political, ideological, or religious objectives. It poses a significant challenge to national security, public safety, and social cohesion.

The objective of the Exploratory Data Analysis(EDA) is to understand the terrorist events around the world. By making use of interactive charts we have tried to make the exploration easy and more informative. We try to have a Birdseye view on global events and observe the trend of attacks across the globe.

#### **Define Your Business Objective?**

Main objective is perform EDA on the given dataset and draw useful conclusions about general trends On GLOBAL TERRORISM and how factors governing Global Terrorism interact with each other.

Terrorism continues to be a pressing global issue with far-reaching consequences for human lives, security, and social stability. However, the lack of a comprehensive and standardized dataset on global terrorism incidents poses significant challenges in understanding the patterns, trends, and underlying factors associated with this phenomenon. This information gap hampers the development of effective counterterrorism strategies, policy formulation, and evidence-based decision-making by governments, security agencies, and researchers.

To address these challenges, there is a critical need for a project focused on creating a Global Terrorism Dataset that collects, cleans, standardizes, and analyzes data on terrorism incidents worldwide. Such a dataset would consolidate information from diverse sources, ensuring consistency and accuracy while providing a comprehensive view of the global terrorism landscape. By establishing a reliable foundation for research and analysis, this dataset would enable a deeper understanding of terrorism, facilitate evidence-based policymaking, and support the development of effective counterterrorism strategies to mitigate the threat posed by terrorism globally.

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required.
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits.

     The additional credits will have advantages over other students during Star Student selection.

             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.


```
# Chart visualization code
```


*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 20 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule.

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries

In [ ]:
# Import Libraries

# numpy and pandas
import numpy as np
import pandas as pd

# visualization tools
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

### Dataset Loading

In [ ]:
# Load Dataset

from google.colab import drive
drive.mount('/content/drive')
filepath = "/content/drive/MyDrive/GLOBAL TERRORISM DATASET/Global Terrorism Data.csv"
terrorism_df=pd.read_csv(filepath,encoding='ISO-8859-1')

### Dataset First View

In [ ]:
# Dataset First Look
terrorism_df

### Dataset Rows & Columns count

In [ ]:
# Dataset Rows & Columns count
print("There are {} rows and {} columns in the dataset".format(terrorism_df.shape[0],terrorism_df.shape[1]))

### Dataset Information

In [ ]:
# Dataset Info
terrorism_df.info()

#### Duplicate Values

In [ ]:
# Dataset Duplicate Value Count
print(len(terrorism_df[terrorism_df.duplicated()]))

#### Missing Values/Null Values

In [ ]:
# Missing Values/Null Values Count

# percentage of missing values in our dataset
missing_values = (((terrorism_df.isnull().sum()).sum())/terrorism_df.size)*100
missing_values

In [ ]:
#Checking for the null values
terrorism_df.isnull().sum()

In [ ]:
# Visualizing the missing values
terrorism_df.isnull()

### What did you know about your dataset?

The above dataset provides us the data on number of terrorist attacks on the basis of year and month on a particluar country and rigion. The corresponding attack type and weapon type is given and the city affected by attack is also given.

The dataset contains **181691** entries with **135** features.

**More than 50% values**  are Null, we need to clean the Dataset first

## ***2. Understanding Your Variables***

In [ ]:
# Dataset Columns
terrorism_df.columns

In [ ]:
terrorism_df.rename(columns={'iyear':'Year','imonth':'Month','iday':'Day','country_txt':'Country','provstate':'State',
                          'region_txt':'Region','attacktype1_txt':'Attack_Type','target1':'Target','nkill':'Killed',
                          'nwound':'Wounded','gname':'Group','targtype1_txt':'Target_Type',
                          'weaptype1_txt':'Weapon_type','latitude':'Latitude',
                          'longitude':'Longitude','target1':'Target','city':'City'},inplace=True)

In [ ]:
# creating dataframe with necessary columns only
terrorism_df = terrorism_df[['Year','Month','Day','Country','State','Region','City','Latitude','Longitude','Attack_Type','Killed',
              'Wounded','Group','Target','Target_Type','Weapon_type']]
terrorism_df.head(10)

In [ ]:
# Dataset Describe
terrorism_df.describe()

### Variables Description

**Year:** Year of attack

**Month:** Month of attack

**Day:** Date of attack

**Country:** Country which is affected

**State:** Sate which is affected

**Region:** Region which is affected

**City:** City with casualities

**Latitude:**

**Longitude:**

**Attack_type:** Type of attack

**Killed:**

**Grounded:**

**Group:** The name of terrorist Group

**Target:**

**Target_type:** Type of target

**Weapon_type:** Type of weapon

### Check Unique Values for each variable.

In [ ]:
# Check Unique Values for each variable.
for i in terrorism_df.columns:
    print(i,terrorism_df[i].nunique())

In [ ]:
#total unique values
terrorism_df.columns.nunique()

## 3. ***Data Wrangling***

### Data Wrangling Code

In [ ]:
# Write your code to make your dataset analysis ready.
terrorism_df.info()

As we can see, 'Wounded' and 'Killed' Attributes have lots of Null values, need to fill null values

In [ ]:
terrorism_df['Wounded'] = terrorism_df['Wounded'].fillna(0).astype(int)
terrorism_df['Killed'] = terrorism_df['Killed'].fillna(0).astype(int)
terrorism_df['Latitude'] = terrorism_df['Latitude'].fillna(0).astype(int)
terrorism_df['Longitude'] = terrorism_df['Longitude'].fillna(0).astype(int)

In [ ]:
terrorism_df.info()

In [ ]:
#cleaned data
terrorism_df.head(10)

### What all manipulations have you done and insights you found?

Answer Here.

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1

In [ ]:
# Chart - 1 visualization code

# attacks by year
plt.figure(figsize=(20,5));
plt.xticks(rotation = 90)
sns.countplot(x=terrorism_df.Year);
plt.xlabel('Attack Year',size=15)
plt.ylabel('Number of Attacks each year',size=15)
plt.title('Attack_of_Years', size=20)
plt.show()

##### 1. Why did you pick the specific chart?

It allows me to quickly assess the distribution and frequency of different Attack types in the dataset.

##### 2. What is/are the insight(s) found from the chart?

2014 appears to be witnessed of a huge terrorist attacks.

2014 onwards recorded a large increase in attacks of terrorism.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Businesses need to assess the potential risk of terrorist attacks during this period. Understanding the historical trends helps in implementing appropriate security measures to mitigate the risks and protect their employees, customers, and assets. This may involve strengthening physical security, implementing surveillance systems, enhancing access controls, and improving emergency response plans.

#### Chart - 2

In [ ]:
# Chart - 2 visualization code

# attacks by Month
plt.figure(figsize=(13,5));
plt.title('Attacks by Month', fontsize = 25)
sns.countplot(x=terrorism_df.Month);
plt.xlabel('Attack Month',size=15)
plt.ylabel('Number of Attacks each Month',size=15)
plt.title('Attack_of_Months', size=20)
plt.show()

##### 1. Why did you pick the specific chart?

It allows me to quickly assess the distribution and frequency of different months that are affected by terrorist attack in the dataset.

##### 2. What is/are the insight(s) found from the chart?

We can find from the chart that May is the most affected month and december is least attacked month in the dataset.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

A high number of terrorist attacks in a specific month can lead to decreased consumer confidence and increased fear among the general population. This may result in reduced consumer spending, particularly in sectors such as tourism, hospitality, and retail.

#### Chart - 3

In [ ]:
# Chart - 3 visualization code

#attack by day
plt.figure(figsize=(20,5));
plt.title('Attacks by Day', fontsize = 25)
sns.countplot(x=terrorism_df.Day);
plt.xlabel('Attack Day',size=15)
plt.ylabel('Number of Attacks each day',size=15)
plt.title('Attack_of_days', size=20)
plt.show()

##### 1. Why did you pick the specific chart?

It allows me to quickly assess the distribution and frequency of different days in a month that are affected by terrorist attack in the dataset.

##### 2. What is/are the insight(s) found from the chart?

From this chart we can see in case of terrorist attcak pattern not that oriented on any specific day.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Terrorist attacks can lead to significant disruptions in business operations. Depending on the scale and severity of the attack, businesses may face challenges in maintaining normal operations, including disruptions to supply chains, transportation, and logistics.

#### Chart - 4

In [ ]:
# Chart - 4 visualization code

#Top 10 most affected countries
plt.subplots(figsize=(16,10))
import seaborn as sns
sns.barplot(x=terrorism_df['Country'].value_counts()[:10].index, y=terrorism_df['Country'].value_counts()[:10].values, palette='husl')
plt.title('Top 10 most affected countries', fontsize =25)
plt.xlabel('Country',size=15)
plt.ylabel('Number of attacks', size=15)
plt.xticks(rotation = 90, size=12)
plt.yticks(rotation = 0, size=12)
plt.show()

##### 1. Why did you pick the specific chart?

The code you provided is generating a bar plot using the Seaborn library to visualize the top 10 most affected countries by terrorist attacks

##### 2. What is/are the insight(s) found from the chart?

We can see from this chart that the most affected country due to terrorist attacks is IRAQ followed by PAKISTAN and AFGANISTAN. INDIA is also afftected by several terrorist attacks and holds the 4th position in the row.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Terrorist attacks can disrupt the overall economy of a country. Business operations may be hampered, causing financial losses for companies operating within the affected area. Infrastructure damage, decreased consumer confidence, and disrupted supply chains can further exacerbate the economic impact.

#### Chart - 5

In [ ]:
# Chart - 5 visualization code

#Top 10 Most Attacked States
plt.subplots(figsize=(15,10))
sns.barplot(x=terrorism_df['State'].value_counts()[:10].index, y=terrorism_df['State'].value_counts()[:10].values, palette='husl')
plt.title('Top 10 Most Attacked States',fontsize=20)
plt.xlabel('States',fontsize=20)
plt.ylabel('Number of Attacks',fontsize=20)
plt.xticks(rotation=90)
plt.show()

##### 1. Why did you pick the specific chart?

The code you provided is generating a bar plot using the Seaborn library to visualize the top 10 most affected States by terrorist attacks

##### 2. What is/are the insight(s) found from the chart?

e can see from this chart that the most affected state due to terrorist attacks is BAGDAD.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

A terrorist attack can disrupt the local economy, causing damage to infrastructure, businesses, and public services. The immediate closure of affected businesses can result in financial losses, decreased consumer spending, and reduced employment opportunities. It can also have a long-term impact on investment, tourism, and overall economic growth.

In [ ]:
plt.subplots(figsize=(15,10))
sns.barplot(x=terrorism_df['Region'].value_counts()[:10].index, y=terrorism_df['Region'].value_counts()[:10].values, palette='husl')
plt.title('Top 10 Most Attacked Region',fontsize=20)
plt.xlabel('Region',fontsize=20)
plt.ylabel('Number of Attacks',fontsize=20)
plt.xticks(rotation=90)
plt.show()

#### Chart - 6

In [ ]:
# Chart - 6 visualization code

#Top 10 Most Attacked Region

plt.figure(figsize = (12,7))
sns.kdeplot(data=terrorism_df, x='Year', hue='Region')
plt.title('Terrorist Activities by Region in each Year',fontsize=25)
plt.xlabel('Years',fontsize=25)
plt.ylabel('Frequency of Attacks',fontsize=25)
plt.xticks(rotation=90)
plt.show()

##### 1. Why did you pick the specific chart?

The chart seems to visualize the number of attacks in different regions, specifically the top 10 most attacked states.

##### 2. What is/are the insight(s) found from the chart?

We can find from this chart that MIDDLE EAST AND NORTH AFRICA is the most affected region in this dataset.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

The occurrence of terrorist attacks in a specific region can disrupt business operations, leading to temporary or long-term closure of facilities, interruptions in the supply chain, or damage to critical infrastructure. This can result in financial losses, decreased productivity, and potential delays in delivering goods or services.

#### Chart - 7

In [ ]:
# Chart - 7 visualization code

#Top 10 most affected City
plt.subplots(figsize=(20,10))
sns.barplot(x=terrorism_df['City'].value_counts()[:10].index, y=terrorism_df['City'].value_counts()[:10].values, palette='husl')
plt.title('Top 10 most affected City', fontsize =25)
plt.xlabel('City', fontsize =25)
plt.ylabel('Number of attacks',fontsize =25)
plt.xticks(rotation =40)
plt.show()

##### 1. Why did you pick the specific chart?

The choice of this specific chart, a bar plot, is suitable for visualizing and comparing the frequency or count of attacks in different cities.

##### 2. What is/are the insight(s) found from the chart?

The chart highlights the top 10 cities with the most recorded attacks. These cities have experienced a higher number of terrorist incidents compared to other cities in the dataset.

From this chart we can insight that most attacks city is BAGHDAD among the known cities.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

This insight can be valuable for businesses operating in or near these cities, as it helps them understand the potential security risks and take appropriate measures to ensure the safety of their operations, employees.

Businesses operating in or planning to expand into areas affected by terrorism can use this information to assess the risks associated with specific cities. They can allocate resources, implement security measures, or adjust business strategies based on the level of threat in different locations.

#### Chart - 8

In [ ]:
# Chart - 8 visualization code

# 10 most attacked targets
plt.figure(figsize=(25,5));
plt.rcParams.update({'font.size':20});
plt.xticks(rotation = 00)
plt.title('Based on Attack type', fontsize = 25)
sns.countplot(y=terrorism_df.Attack_Type);

##### 1. Why did you pick the specific chart?

This chart suggests the use of a bar chart (specifically a countplot) to visualize the number of terrorist attacks Based on Attack type in an exploratory data analysis (EDA).

##### 2. What is/are the insight(s) found from the chart?

We can find from this chart that BOMBING/EXPLOSION is the most favorite Attack type by the Terroriest gang in this dataset.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

The findings highlight the prevalence of private bombing and explosion as a major attack type. This can prompt businesses to reassess their security measures and protocols to better protect their premises, employees, and assets. It may involve strengthening physical security, implementing stricter access controls, and enhancing surveillance systems.

#### Chart - 9

In [ ]:
# Chart - 9 visualization code

# Number of Deaths in different years
plt.figure(figsize = (12,7))
terrorism_df.groupby(['Year'])['Killed'].sum().plot(kind='bar',colormap='summer')
plt.title('Number of Deaths in different years',fontsize=15)
plt.xlabel('Years',fontsize=15)
plt.ylabel('Number of Deaths',fontsize=15)
plt.xticks(rotation=90,size=11)
plt.yticks(rotation=00,size=11)
plt.show()

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Number of deaths caused by terrorism is more between 2014 and 2018, with on an average >50K people being killed. High peak went to 2014 with 45K+ deaths.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 10

In [ ]:
# Chart - 10 visualization code

# Number of Wounded People in different years
plt.figure(figsize = (12,7))
terrorism_df.groupby(['Year'])['Wounded'].sum().plot(kind='bar',colormap='summer')
plt.title('Number of Wounded People in different years',fontsize=15)
plt.xlabel('Years',fontsize=15)
plt.ylabel('Number of Wounded People',fontsize=15)
plt.xticks(rotation=90,size=11)
plt.yticks(rotation=00,size=11)
plt.show()

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 11

In [ ]:
# Chart - 11 visualization code

# Top 10 Terrorist Organization with Highest Terror Attacks
plt.figure(figsize=(10,5))
sns.barplot(y=terrorism_df['Group'].value_counts()[:10].index, x=terrorism_df['Group'].value_counts()[:10].values, palette='husl')
plt.title('Top 10 Terrorist Organization with Highest Terror Attacks',fontsize=14)
plt.ylabel('Terrorist Groups',fontsize=15)
plt.xlabel('Number of Attacks',fontsize=15)
plt.xticks(rotation=0)
plt.show()

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 12

In [ ]:
# Chart - 12 visualization code

plt.figure(figsize=(10,5))
sns.barplot(y=terrorism_df['Target'].value_counts()[:10].index, x=terrorism_df['Target'].value_counts()[:10].values, palette='husl')
plt.title('Top 10 Terrorist Organization with Highest Terror Attacks',fontsize=14)
plt.ylabel('Terrorist Groups',fontsize=15)
plt.xlabel('Number of Attacks',fontsize=15)
plt.xticks(rotation=0)
plt.show()

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 13

In [ ]:
# Chart - 13 visualization code

# Top 5 most used weapons types in terror attacks
plt.figure(figsize=(10,7))
sns.barplot(x=terrorism_df['Weapon_type'].value_counts().head().index, y=terrorism_df['Weapon_type'].value_counts().head().values,palette='flare')
plt.title('Top 5 Most Used Weapon types',fontsize=15)
plt.xlabel('Weapon Types',fontsize=15)
plt.ylabel('Number of Weapon Used',fontsize=15)
plt.show()

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

In [ ]:
terrorism_df.hist(figsize=(20,10))
plt.show()

In [ ]:
# creating new dataframe for the year 2014
terr_df_2014 = terrorism_df[terrorism_df.Year == 2014]

In [ ]:
plt.subplot(1,2,1)
terr_df_2014.groupby(['Country'])['Killed'].sum().sort_values(ascending = False).head(10).plot(kind='bar',colormap='RdBu')
plt.title('Top 10 countries with max people killed in 2014',fontsize=15)
plt.xlabel('Country',fontsize=15)
plt.ylabel('Number of people killed ',fontsize=15)
plt.xticks(rotation=90)

plt.subplot(1,2,2)
terr_df_2014.groupby(['Country'])['Wounded'].sum().sort_values(ascending = False).head(10).plot(kind='bar',colormap='spring')
plt.title('Top 10 countries with max people wounded in 2014',fontsize=15)
plt.xlabel('Country',fontsize=15)
plt.ylabel('Number of people Wounded',fontsize=15)
plt.xticks(rotation=90)
plt.gcf().set_size_inches(15, 5)

#### Chart - 14 - Correlation Heatmap

In [ ]:
# Correlation Heatmap visualization code

plt.figure(figsize=(10,10))

#This shows how much related is one parameter to the other in the dataset.

sns.heatmap(np.round(terrorism_df.corr(),2),annot=True,cmap='BuPu')

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

#### Chart - 15 - Pair Plot

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ?
Explain Briefly.

Answer Here.

# **Conclusion**

After observing different graphs, we obtained the following results:

Explosive : Most used weapon type in attacks

2014 : Most number of attacks year

5th month(May) : Most number of attacks month

15th day of month : Most number of attacks day

Iraq : Most attacked country

Baghdad : Most attacked State

Middle East and North America : Most attacked region

Private Citizens and Property : Most attack based on target type

Bombing /Explosion : Most attack based on attack type

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***